### ISSUE TITLE
Help with Spark LSTM example

### ISSUE THREAD

**Issue by tomthetrainer** [SkymindIO/dsx#1]
@wmeddie @eraly @turambar 

I am having trouble with the UCI classification example when I try to port it to spark. 

Can you advise or assist? 

Here is some background. 

It needs to run on the Spark on Demand Cluster on IBM Data Science Experience. This is for a Coursera course we are co-producing. 

To test on a reasonably similar environment you can install spark and do the following. 
On my Mac I do this..

```
Brew Install Spark
/usr/local/Cellar/apache-spark/2.2.0/libexec/sbin/start-master.sh
Go to http://localhost:8080 to get the url for spark master 
/usr/local/Cellar/apache-spark/2.2.0/libexec/sbin/start-slave.sh <spark master from above>
```

To run these examples I ship an uber jar, the jar can be built with '''mvn package.''' 

I put a recent build in the Release so you can explore the current state of affairs. 

Here are the classes I built as I explored a way to get this all to work. 

## Big Picture

I ship the data with a --files attribute to spark-submit, this makes it available in the working directory of each worker. 

## spark.py

I built a python script to explore the environment, nothing really to see here, but it is an example to explore the working directory during a spark job. 

```
spark-submit  \
--master spark://Toms-MacBook-Pro.local:7077 \
--files iris_train.txt \
spark.py
```
### App2

This runs and is iris classifier but it makes no use of Spark Context, this was my first test you can ignore it. 

### SparkApp

To see if I could get a basic read, process, train pipeline going I started with iris. This works. It uses Spark. I had issues with Evaluation so that is a little hacked. 

### Overview: 
ships two iris csv files reads them and executes

spark-submit  --master spark://Toms-MacBook-Pro.local:7077 --files iris_test.txt,iris_train.txt --class skymind.dsx.SparkApp  dl4j-quickstart-1.0-SNAPSHOT-jar-with-dependencies.jar

You might miss it with all the Spark output, but it does complete and logs an evaluation to STDOUT.

### UCISequenceClassificationLocalSpark1, and Spark2

This is just the UCI demo I am trying to move to Spark

#### UCISequenceClassificationSpark1

This one just validates unziping the data into local cache

#### UCISequenceClassificationSpark2

This is the example I am trying to get to work. 

Status: 
It runs with..

```
spark-submit  --master spark://Toms-MacBook-Pro.local:7077 --files uci.zip --class skymind.dsx.UCISequenceClassificationSpark2 dl4j-quickstart-1.0-SNAPSHOT-jar-with-dependencies.jar
```

Honestly it seems to train, but I do not know how to validate that, I think I am messing up the evaluation? I get

```
54285 [main] INFO skymind.dsx.UCISequenceClassificationSpark2  - Test set evaluation at epoch 0: Accuracy = 0.00, F1 = NaN
59217 [main] INFO skymind.dsx.UCISequenceClassificationSpark2  - Test set evaluation at epoch 1: Accuracy = 0.00, F1 = NaN
63950 [main] INFO skymind.dsx.UCISequenceClassificationSpark2  - Test set evaluation at epoch 2: Accuracy = 0.00, F1 = NaN
68712 [main] INFO skymind.dsx.UCISequenceClassificationSpark2  - Test set evaluation at epoch 3: Accuracy = 0.00, F1 = NaN
```

**Comment by AlexDBlack** [comment]
@tomthetrainer My first guess: you are running into a known issue with evaluation.
Try the workaround listed here: https://deeplearning4j.org/releasenotes#zeronineone

**Comment by tomthetrainer** [comment]
@AlexDBlack 
That fixed it, thanks !!!
